### ISSUE TITLE
Vessel mover dropping heavy large vessels

### ISSUE THREAD

**Issue by SpannerMonkey** [PapaJoesSoup/VesselMover#1]
HI. When using vessel mover to move a vessel using  ( mainly seagoing) the default first position (green marker ring ) the vessel is moved without issue, however on placing the vessel at first drops slowly and then goes into free fall, falling the last few meters and often landing with enough force to destroy vessel parts.  The same happens although to a lesser extent with the lowest (orange?) height and speed option. 
Replication requires large boat pack or similar , construct vessel of several thousand tonnes (easier than you'd imagine) Launch and move to water and place, observe.
Cheers

**Comment by PapaJoesSoup** [comment]
Added a new movement mode called Fine.  lowers altitude to 5 meters.  should eliminate fall damage.

**Comment by gomker** [comment]
I am still seeing issues where parts are being destroyed on drop. 
The "Fine" mode altitude shows at 15 meters for me and it seems to go into freefall at about 8 meters.

**Comment by gomker** [comment]
@PapaJoesSoup  I notice that when I am in "Fine" mode and click Place Vessel, that it switches to "Normal" mode. Maybe this is why the drop speed increases again
