### ISSUE TITLE
1.2 Testing - Vessel spawns on ocean floor even without Launch enhancers

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/VesselMover#12]
I have another open issue related to this in #4 
This is in 1.2pr spawning a craft when over water spawns vessel under water for a few frames then it warps to above sea level breaking many parts.
I know from my own mods Altitude calculations have changed a bit.

I see some terrain calcs commented out [here](https://github.com/PapaJoesSoup/VesselMover/blob/master/VesselSpawn.cs#L309)

**Comment by DoctorDavinci** [comment]
Confirmed ... When spawning a vessel it will be spawned on the sea floor for a split second and then warps to the surface

The destruction of the craft being spawned is dependent on the depth at which the sea floor sits. See Video below (NOTE: video has been sped up to 1.5)

I'm not sure if mass, displacement or size are a factor as well ... further testing would be needed to determine this

Video: https://youtu.be/BE7Edqn2YT0

Log File: https://www.dropbox.com/s/tdfescaq1q7396s/KSP%20-%20VM%20Git%20Issue%20%2312.log?dl=0
Save File: https://www.dropbox.com/s/2ht68jerbc83u30/VM%20Git%20issue%20%2312.sfs?dl=0

**Comment by gomker** [comment]
It would be preferable if the sequence that spawns the vessel detects the water and sets the altitude above Sea Level. Similar to something like

`
public double TrueAlt()
{
    Vector3 pos= this.part.transform.position; //or this.vessel.GetWorldPos3D()
    double ASL = FlightGlobals.getAltitudeAtPos(pos);
    if (this.vessel.mainBody.pqsController == null) { return ASL; }
    double terrainAlt = this.vessel.pqsAltitude;
    if (this.vessel.mainBody.ocean && terrainAltitude <= 0) { return ASL; } //Checks for oceans
    return ASL - terrainAlt;
}`

**Comment by gomker** [comment]
Also wanted to clarify, spawning under water only seemed to occur if launch clamps were on the vessel in 1.13. However, if I am mistaken, I never saw any vessels (even large ones) take damage when teleporting to the 35M hard coded height.

**Comment by DoctorDavinci** [comment]
So in regards to exploding vessels at a certain depth, I found this thread on the forum: http://forum.kerbalspaceprogram.com/index.php?/topic/147983-vessels-exploding-at-depths-of-90-meters/

Seems that parts have a max pressure at which they will fail underwater and that would explain the results of my testing

It is clear that VM is spawning vessels on the sea floor for a fraction of a second before warping to the surface which, if the sea floor is below 90 meters from the surface, will cause some parts to explode due to over pressure according to the forum thread

**Comment by gomker** [comment]
Issue really isn't about the vessel exploding,  why would a vessel spawn underwater if they mouse raycast is picking a point on the surface?  I do see that there was already code to detect oceans and spawn correctly based on ASL however, something is different in 1.2 going from protoVessel to vessel.

I have been trying to figure it out but not much luck so far, you can see it in action if you put a breakpoint here - https://github.com/PapaJoesSoup/VesselMover/blob/master/VesselSpawn.cs#L640

The vessel altitude when spawning will always be the the surface of the reference body, I have even attempted just hard coding it everywhere the altitude was set without effect.

**Comment by gomker** [comment]
Fixed in latest PR
