### ISSUE TITLE
1.2 Testing - Vessels in motion are breaking apart

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/VesselMover#14]
This is new to 1.2,  my large vessels are falling apart due to some forces being applied when moving.  Usually when using "ludicrous" speed but sometimes on normal the vessel sometimes collides with itself, I see parts noting they crashed into each other, and fall apart

![screenshot0](https://cloud.githubusercontent.com/assets/3577339/18612828/95066b5a-7d2a-11e6-9dbd-a89bb80124a1.png)

**Comment by gomker** [comment]
Here is a video capture of it in action. I can trigger it more quickly by changing directions, or pressing two directions simultaneously while moving, i.e. pressing W and A 

https://youtu.be/YAUHgbANS-s

**Comment by gomker** [comment]
@PapaJoesSoup  Do you have a dev branch that maybe I could do a PR to? I only had a few small changes that I think fixed the issues.

**Comment by PapaJoesSoup** [comment]
Just do the pr off the master.  I'm the only one in it at this time.

**Comment by gomker** [comment]
Fixed in merged PR
