### ISSUE TITLE
Add crew selection capability

### ISSUE THREAD

**Issue by TheDestroyer111** [PapaJoesSoup/VesselMover#17]
Right now the mod assigns one totally new crew member that didn't even appear in the astronaut complex to a spawned vessel. I think it should assign availible astronauts from the astronaut complex for default and hire new ones if nobody is availible, but allow the player to select astronauts like in SPH/VAB too.

**Comment by gomker** [comment]
When spawning from a Vessel from protoVessel you can add a crew member but it is done programatically - see [here](https://github.com/PapaJoesSoup/VesselMover/blob/master/VesselSpawn.cs#L455) 

The ability to pick crew and assign to vessel are part of different Scenes of KSP and I do not think that it would be feasible to integrate in a seamless way.  The Astronaut complex is a complete scene itself and I do not see a way to call a "kerbal" browser the way we call "[CraftBrowser](https://github.com/PapaJoesSoup/VesselMover/blob/master/VesselSpawn.cs#L111)"

**Comment by Nerfclasher** [comment]
I did find something that could let you chose your crew if someone could make a pull request that would help the team save time so look at this and the requirements are it must be compiled against KSP 1.2 and it must use this code reference https://kerbalspaceprogram.com/api/_crew_assignment_dialog_8cs.html

**Comment by PapaJoesSoup** [comment]
I researched the suggestion that Nerfclasher provided, and determined that the necessary hooks are not publicly available.  I will have to create a selection list via script.  In work.

**Comment by PapaJoesSoup** [comment]
Added feature to select one crew member from a list of available crew during spawn  Will be included in v1.7.2.3
