### ISSUE TITLE
Remove placement cursor on F2

### ISSUE THREAD

**Issue by KSAMissionCtrl** [PapaJoesSoup/VesselMover#18]
When the user hides the interface, it would be great if the placement cursor hides too. You now have a static object in mid-air and can take your time setting up that perfect photo...

**Comment by gomker** [comment]
I know where the code spawns this - just need to figure out how to bind it to F2 which should not be too difficult

**Comment by DoctorDavinci** [comment]
https://github.com/PapaJoesSoup/BDArmory/issues/6

Possibly related?
