### ISSUE TITLE
Enhancement - Ease jump out vessel on load/coming out of rail

### ISSUE THREAD

**Issue by Brusura** [PapaJoesSoup/VesselMover#2]
Hello, I have a request, would it be possible to extend the gentle landing provided by this mod to all landed vessels in game to avoid the occasional jump and explosion on scene load?

**Comment by gomker** [comment]
Have you tried using [Kerbal Joint Reinforcement mod](http://forum.kerbalspaceprogram.com/index.php?/topic/50911-113-kerbal-joint-reinforcement-v32-63016-now-with-win64-compatibility/) it includes the functionality you described.

If the devs add this function it may conflict with this mod as it is used by many - but I will let them respond to that assumption.

**Comment by Brusura** [comment]
Hello
Yes I am using KJR, but every base even small one sometimes on load they compenetrate the terrain resulting in jump out in low gravity world or explosion. As a work around, I thought of loading them at , say 10 meters above ground, and then gently let them touch down.

Il giorno 06/ago/2016, alle ore 18:17, Derek Lane <notifications@github.com> ha scritto:

Have you tried using Kerbal Joint Reinforcement mod it includes the functionality you described.

If the devs add this function it may conflict with this mod as it is used by many - but I will let them respond to that assumption.

**Comment by gomker** [comment]
Ah , I see what you mean. I see the same problem with large boats like Carriers.
To work around this I put Launch Stability enhancers all around the craft.

**Comment by Brusura** [comment]
Yeah , but it not really a solution of you are building a base in the mun with KIS , how do you put this launch stability enhancer ? Do you mean launch clamps? If so are not they only attachable in vab/sph?




Il giorno 10/ago/2016, alle ore 20:00, Derek Lane <notifications@github.com> ha scritto:

Ah , I see what you mean. I see the same problem with large boats like Carriers.
To work around this I put Launch Stability enhancers all around the craft.

**Comment by gomker** [comment]
So if I understand this correctly you are building a very large base w/ KIS , then moving it?
Or do you have a pre built one then loading it with VesselMover?

**Comment by PapaJoesSoup** [comment]
In either case, the new setting "FINE" in the latest release  should work, assuming the target location is level.  At 5 meters, the landing should be gentle wnough...

**Comment by Brusura** [comment]
Sorry if I can not make my self clear enough....my point was to extend and replace to all landed craft the function provided by this mod, because stock often move and make jump landed crafts when the scene load.




Il giorno 11/ago/2016, alle ore 16:45, Joseph Korinek <notifications@github.com> ha scritto:

In either case, the new setting "FINE" in the latest release should work, assuming the target location is level. At 5 meters, the landing should be gentle wnough...

**Comment by gomker** [comment]
1.2 changes quite a bit with Physics load. Updates to VesselMover should help when moving large vessels however, you may need to have "Unbreakable Joints" turned on in cheats.  Myself and others who use Large Boats Pack experience the same issues.

Look for the 1.2 release of Vessel Mover to come out shortly which will have this stabilization code. I will close this issue out for now and you can reopen later if you feel that the issue persists.
