### ISSUE TITLE
V Spawn Vessel function spawns a vessel with an external command seat with crew in the protoModuleCrew list

### ISSUE THREAD

**Issue by linuxgurugamer** [PapaJoesSoup/VesselMover#24]
Take Command and Vessel Movers' Spawn Vessel function aren't playing nicely with each other

REPLICATION STEPS

1. Launch probe.
2. Spawn vessel with command seat using VM and no kerbal is in the seat
3. Place spawned craft on ground (still no kerbal)
4. press escape and exit to space center
5. click on craft missing kerbal and choose to fly it
6. kerbal is in seat now

Apparently, when VM spawns a craft like this, there will be a crewmember already in the protoModuleCrew of the part.  This is wrong.

**Comment by gomker** [comment]
Related to #17

**Comment by gomker** [comment]
Better late than never :) adding an option to not add crew member during spawn of vessel.

**Comment by gomker** [comment]
Added option in last release
