### ISSUE TITLE
Impact with terrain after adjusting vessel height

### ISSUE THREAD

**Issue by KSAMissionCtrl** [PapaJoesSoup/VesselMover#29]
Thanks for implementing the ability to change the height of the vessel! It doesn't seem to snap properly back to the default settings when you tab through them however, and if you made it lower than normal when it drops to the very fine setting it will try to go through the ground. BOOM! :P

**Comment by PapaJoesSoup** [comment]
Fix in place.  code now detects when over water or land.  Prevents placing craft below the surface unless in water.  Mode changes no longer position craft underground.  Additionally, changes made to make altitude changes more intuitive, and if changing altitude manually, movement mode changes no longer change the current altitude of the craft.  Added a reset button (Throttle Cuttoff) to reset this behavior back to default.

Will be released with version 1.7.3
