### ISSUE TITLE
Add option "drop vessel"

### ISSUE THREAD

**Issue by Brusura** [PapaJoesSoup/VesselMover#3]
Sometimes I just need to bring a capsule or a rocket to an height and test it parachute or engine on the reentry

**Comment by TheDestroyer111** [comment]
Hyperedit is better for this :D 
But seriously, although this is kind of out of the scope of the idea behind VesselMover, AFAIK there is no good mod that could place vessels inside the atmosphere (hyperedit is glitchy and very hard to use in this way, i didn't yet figure out how to use the orbit editor to get planes moving in the atmosphere without making hyperedit say that target location is underground).

**Comment by PapaJoesSoup** [comment]
Looking at this feature now.  Seems it can be added without too much trouble.

**Comment by PapaJoesSoup** [comment]
Feature added.  will be in next release. 1.7.2
