### ISSUE TITLE
VesselMover dosent use save files, only uses stock files

### ISSUE THREAD

**Issue by Pounicoss** [PapaJoesSoup/VesselMover#31]
when i can just move my saves to the stock files, it would be better if it would use the save files aswell

**Comment by PapaJoesSoup** [comment]
Examined issue.  Code was passing title of game and not save folder.  KSP CraftDialog uses folder as part of the craft search.  if the game save is copied and the folder renamed, the game name is not changed.  This results in the wrong folder being used.  

Corrected code to use the game save folder name.  now works correctly.  

Fix to be included in v 1.7.1
