### ISSUE TITLE
Control window ignores F2

### ISSUE THREAD

**Issue by KSAMissionCtrl** [PapaJoesSoup/VesselMover#44]
So, I updated to KSP v1.3.1 and the latest VesselMover and was psyched to see that the cursor around the aircraft now hides when I press F2! Unfortunately the control window still being visible kind of ruins the shot ;P It's not too hard to paint out in most situations but still, would be nice if it went away too.

All that being said, although I know I requested the feature of having the movement cursor hide on F2 I didn't see any mention of it in the release notes so I'm wondering if this is just a thing that happens to occur KSP v1.3.1?? (regardless, would still like the control window to obey the F2 command)

**Comment by PapaJoesSoup** [comment]
It does look like support for show/hide UI was added for the cursor but not the window.

Added support for F2 (or whatever you set the Show/Hide UI toggle key to).
Improved behavior of cursor display to be more reliable with turning on and off of UI.  Was previously too sensitive and could result in a mismatch with the Show/Hide UI setting.
