### ISSUE TITLE
Cannot see vesselmover icon

### ISSUE THREAD

**Issue by Alphasus** [PapaJoesSoup/VesselMover#5]
LOG: https://drive.google.com/open?id=0B3IvrPbGhZWFem9HVXR2QmVKZVE
GameData folder: https://drive.google.com/open?id=0B3IvrPbGhZWFc0w0M25BT1VHZEE
My mods:
B9 Aerospace 6.1.2
BDArmory 0.11.1.2
Environmental Visual Enhancements 1.1-1
Scatterer v0.0247
VesselMover 1.5.1
ModuleManager 2.6.5
Hyperedit
Reproduiction Steps
1. Launch any craft.
2. VesselMover icon(upper right next to the BDA button in theory) shouldn't be visible with that GameData folder.

**Comment by DoctorDavinci** [comment]
Did you put the vesselmover folder that is in the gamedata folder contained in the zip file into your gamedata folder or did you just drop the gamedata folder into your gamedata folder?

**Comment by Alphasus** [comment]
I'll reinstall the way that you suggested when I get back home in a few hours. I don't remember how I installed VesselMover.

**Comment by DoctorDavinci** [comment]
If you have a gamedata folder inside of your KSP/gamedata folder then the mod is installed incorrectly

**Comment by Alphasus** [comment]
I just checked my Drive, which has a copy of my current GameData folder. The mod is installed properly.

**Comment by Alphasus** [comment]
This is fixed now. Just reinstalled.
