### ISSUE TITLE
Ludicrous mode is missing

### ISSUE THREAD

**Issue by Nerfclasher** [PapaJoesSoup/VesselMover#7]

**Comment by PapaJoesSoup** [comment]
Duplicate of #6

**Comment by Nerfclasher** [comment]
Number #6 issue ludicrous mode is still missing

**Comment by PapaJoesSoup** [comment]
Hmm maybe I uploaded the wrong archive...

**Comment by PapaJoesSoup** [comment]
Makes no sense though.  Doc tested and confirmed that all 4 settings were there.  Check your installation

**Comment by PapaJoesSoup** [comment]
Did you pull from git or spacedock?
