### ISSUE TITLE
Moving a craft that is landed on another craft causing clipping / explosion

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/VesselMover#8]
I understand this may be out of scope for how the tool was designed, you can consider this an enhancement request.

While trying to move something on an aircraft carrier the ship seems to dip slightly into the landed vessel below and explode.
You can see the issue here in action : https://youtu.be/4yIk0q3xtE8

The tool seems to first set height [based on what level of speed you are moving](https://github.com/PapaJoesSoup/VesselMover/blob/master/VesselMove.cs#L34)
And then will detect anything below to be able to float above. Not sure how its detecting landed vessels but I do see its detecting surface [here](https://github.com/PapaJoesSoup/VesselMover/blob/master/VesselMove.cs#L34)

Could this be refactored to detect what is below first and  add +1 meter to keep collision from occurring?

**Comment by gomker** [comment]
So I just realized that it will not detect a landed vessel through a bit more testing, it just happened that my carrier was just high enough for the default vessel mover height.

**Comment by PapaJoesSoup** [comment]
Interesting.  The height values used are hardcoded.  There is no reason that they could not be changed.  In fact, we may be able to allow adjustment via the gui.

**Comment by gomker** [comment]
That would be an elegant solution , maybe a slider or +/- adjust. This would solve any of my use cases , perhaps even Issue #2 if he is loading large bases from Vessel Mover

**Comment by gomker** [comment]
added in latest referenced PR above solves issue
